WIP: Select Pedals
berarma/oversteer pull request #90
Opened 2022-01-17 18:24 UTC by hodasemi

Hi,

as follow up from the discussion in #89 I started working on a solution. I added a ComboBox above the combine pedals area to select from which source the input should come from.

![grafik](https://user-images.githubusercontent.com/13390692/149820808-9fd0f154-e6b1-4762-8871-b75f676f03c5.png)
![grafik](https://user-images.githubusercontent.com/13390692/149820821-03015a69-6137-458b-a399-d9868bbe29ae.png)

There will always be the 'Default' option, because I guess there is no way to check if pedals are actually connected to the wheel base. The current work only adds to the UI, queries possible devices and adds it to the ComboBox. I think the missing parts are

* [ ] use the selected pedal as input source and display its use below
* [ ] store the pedal selection in the profile

--- 

The ultimate goal should be

* [ ] create virtual device to combine the source devices

2022-01-17 19:41 UTC, irseny commented
Would the combined virtual device be compatible with force feedback though?
I do not know the details in linux so I might be wrong about this:
I think the virtual device would have to advertise FFB capabilities and also forward the game's FFB signals to the wheel device?

2022-01-17 19:56 UTC, hodasemi commented
I guess so. I don't know these things either, but that information must be out there somewhere ...
I would at least try to solve the problem.

2022-01-17 21:13 UTC, berarma commented
I think this PR should be about adding multi-device support without creating any virtual device. That should be left for another PR in case anyone wants to do the work. Although I still think it would be better to do that work towards a more generic app.

I would like the devices to be shown together, the pedal selection combo directly below the wheel. Later, more devices could be added like shifter and handbrake.

I can't review the code now but will do. Feel free to keep working on it in the mean time.

2022-01-23 16:12 UTC, hodasemi commented
The core features are now in place. You can now review the code.

This is how it looks:
![grafik](https://user-images.githubusercontent.com/13390692/150687219-5312572f-048f-4855-8b41-6967a67f3dc3.png)

Currently you can only view the behavior inside oversteer. There is no virtual device that routs input into a single device. I agree that it would be better to make it more general, that the users can map the axes they need to the correct one, instead of hard coding them for each and every device. 
Sadly this still doesn't solve the core issue I tried to solve. I will take a deeper look into virtual devices, especially routing force feedback back to the physical device.

2022-01-25 14:55 UTC, berarma requested changes
It looks pretty good. There's some things I'd change before merging that I've commented in the reviewed code. And then, I'm not sure about the way to handle multi-devices, I think it should be more flexible for accepting more devices later, but that can be worked after merging into a custom development branch.

Why is `update_pedal_list` so different to `update_device_list`? I hoped it would be almost the same code but using different id lists.

2022-01-25 14:55 UTC, berarma commented on data/udev/99-thrustmaster-pedal-perms.rules
> +# Match kernel name of device, rather than ATTRS{idProduct} and ATTRS{idVendor}
I'd rather put it in the thrustmaster udev file despite having "wheel" in its name. I don't feel like creating many more udev files.

2022-01-26 09:38 UTC, hodasemi commented
> Why is `update_pedal_list` so different to `update_device_list`? I hoped it would be almost the same code but using different id lists.

This is what I also thought. The problem is that the entry that has a `ID_FOR_SEAT` does not have `DEVNAME`. Thus, I couldn't use the created entry for like anything at all. I decided to sort by usb-id and puzzle the required information together.

2022-01-26 09:39 UTC, hodasemi commented on oversteer/gui.py
> +        if self.pedals:
The filtering of the pedals is done in the exact next line if there is pedal present in `filter_pedal_input`.

2022-01-26 09:57 UTC, berarma approved these changes

2022-01-26 09:59 UTC, berarma commented
Thanks! I'll shortly merge this in a new branch to test it more and maybe ready it to add more devices, like shifters and handbrakes. This could lead to more cool things.

2022-01-27 12:25 UTC, berarma commented
I've created a branch named `multidevice` with these changes to work towards a multidevice app.

2022-01-27 12:25 UTC, closed without merging